package handler

import (
	"encoding/json"
	"fmt"
	"net/http"
)

var oauthResult = `
{
	"access_token": "8s2wfclhyp5iiikowm3ocnfalt7qfl7es8xhuda3ttusslssx6c14hq7yocp62c5",
	"created_at": 1451528865,
	"expires_in": 7776000,
	"token_type": "bearer"
	}
`
var clientId = "test_id"
var clientSecret = "test_secret"
var password = "battmobiel"
var email = "kdebacker@sofico.be"
var grantType = "password"

var accessToken = "8s2wfclhyp5iiikowm3ocnfalt7qfl7es8xhuda3ttusslssx6c14hq7yocp62c5"

type AutoGenerated struct {
	GrantType    string `json:"grant_type"`
	ClientID     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	Email        string `json:"email"`
	Password     string `json:"password"`
}

//OAuthHandler locks the teslaj
func OAuthHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Need POST request", http.StatusBadRequest)
		return
	}
	var credentials AutoGenerated
	err := json.NewDecoder(r.Body).Decode(&credentials)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if credentials.Password != password || credentials.ClientID != clientId ||
		credentials.ClientSecret != clientSecret || credentials.Email != email ||
		credentials.GrantType != grantType {
		http.Error(w, "missing something from request body", http.StatusBadRequest)
		return
	}
	fmt.Fprintf(w, oauthResult)
	w.Header().Set("Content-Type", "application/json")
}
